name: Docker Image CI

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:

  build-and-deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYY.MM.DD
      
    - name: OIDC Login via Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to the container registry
      run: az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build the image
      run: |
        docker build . -f Dockerfile -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.CONTAINER_IMAGE_NAME }}:${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }} -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.CONTAINER_IMAGE_NAME }}:latest
    
    - name: Push image
      run: |
        docker push --all-tags ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.CONTAINER_IMAGE_NAME }}
    
    - name: Scan image for vulnerabilities
      uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.CONTAINER_IMAGE_NAME }}:${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }}
